### ISSUE TITLE
Check status of allow_url_fopen during activation

### ISSUE THREAD

**Issue by marty-jensen** [graybirchsolutions/amc-activities-shortcode#17]
The query request to retrieve events from the AMC feed fails and throws an exception if allow_url_fopen is set to 'Off' in php.ini.

Add a check for this flag as an activation hook and prevent plugin activation without it.

**Comment by chaoranxie** [comment]
I created an tested a change here https://github.com/chaoranxie/amc-activities-shortcode/pull/new/add_activation_for_allow_url_fopen

I tested it by modify `php.ini` file and alternating between
allow_url_fopen = On
allow_url_fopen = Off
When it is Off, i get the following error "The allow_url_fopen setting is not enabled." (screenshot attached)
![WordPress_›_Error](https://user-images.githubusercontent.com/722794/235775243-e7aeac51-f984-46b1-b626-c7919c8cfe26.png)
